bldr:
    profiles:
        spec:
            description: Profile to run test suite
            tasks:
                - runSpec
        bdd:
            description: Local Development Profile
            tasks:
                - runSpec
                - watch
        cs:
            description: fix cs for once
            tasks:
                - runFixer
        rebase:
            description: Rebase flow
            tasks:
                - gushRebase
        merge:
            description: merge flow
            tasks:
                - gushMerge
